//! Keep `COMMANDS` in sync with `command_handlers!` in `src/commands/mod.rs`.
//! Listing them here flips Tauri ACL from “every window may invoke everything”
//! to deny-by-default; each capability then opts in with `allow-<kebab-name>`.

fn main() {
    // Snake_case command names → autogenerated `allow-foo-bar` / `deny-foo-bar`.
    const COMMANDS: &[&str] = &[
        // recording
        "list_capture_sources",
        "list_capture_devices",
        "platform_capabilities",
        "check_permissions",
        "request_screen_permission",
        "open_screen_recording_settings",
        "relaunch",
        "recorder_state",
        "start_recording",
        "pause_recording",
        "resume_recording",
        "stop_recording",
        "pick_capture_area",
        "complete_area_pick",
        "cancel_area_pick",
        "show_area_frame_guide",
        "hide_area_frame_guide",
        "begin_camera_file",
        "write_camera_chunk",
        "finish_camera_file",
        "begin_mic_file",
        "write_mic_chunk",
        "finish_mic_file",
        "hide_recorder",
        "set_recorder_layout",
        "set_recorder_bar_width",
        "show_camera_preview",
        "hide_camera_preview",
        "dismiss_camera_preview",
        "set_camera_preview_visible",
        "flush_camera_capture",
        "flush_mic_capture",
        "show_annotation_overlay",
        "hide_annotation_overlay",
        "set_annotation_display_follow",
        "open_library",
        "open_editor",
        "present_window",
        // captions
        "get_whisper_model_status",
        "download_whisper_model",
        "delete_whisper_model",
        "generate_captions",
        // projects
        "list_projects",
        "load_project",
        "ensure_proxy",
        "save_editor_state",
        "rename_project",
        "delete_project",
        "ensure_thumbnail",
        // export
        "ensure_seekable_recording",
        "begin_export",
        "write_export_chunk",
        "finish_export",
        "abort_export",
        "mux_export_audio",
        "prepare_export_audio",
        "attach_export_audio",
        "remove_temp_file",
    ];

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
